[package]
name = "transp-test"
version = "0.1.0"
edition = "2021"

[dependencies]
eframe = { version = "0.29.1" }
egui = "0.29.1"
tracing-subscriber = { version = "0.3.18", features = [
  "json",
  "fmt",
  "env-filter",
] }
